INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES(1, 'HOME');
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES(2, 'ELECTRONICS');
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES(3, 'TOOLS');
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES(4, 'CLOTHES');
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES(5, 'ENTERTAINMENT');
INSERT INTO PRODUCT_CATEGORY(ID, NAME) VALUES(6, 'HEALTH');

INSERT INTO PRODUCT(ID, UUID, PRODUCT_CATEGORY_ID, NAME, PRICE)
VALUES(1, '910a29f8-bab3-4138-a40d-b722671be58a', 1, 'Bed', 30.99);