version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
  spring:
    image: spring-boot-shop:latest
    container_name: spring-boot
    restart: on-failure
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shop
      - SPRING_DATASOURCE_USERNAME=shop
      - SPRING_DATASOURCE_PASSWORD=shop
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=8010
    ports:
      - "8010:8010"
    depends_on:
      - postgres