server:
  port: 8010
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4000/shop
    username: shop
    password: shop
  flyway:
    enabled: true
    locations: "classpath:/db/migration"
  jpa:
    open-in-view: false
    show-sql: false