server:
  port: 8010

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: shop
    password: shop
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop