micronaut:
  application:
    name: shop
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc://postgresql://localhost:4010/shop
    username: shop
    password: shop