micronaut:
  application:
    name: shop
  server:
    port: 8020
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:4010/shop
    username: shop
    password: shop
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: "pl.wit.shop.product.domain"
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
      show_sql: true