micronaut:
  application:
    name: shop
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
    jdbc-url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:4010/shop}
    username: ${POSTGRES_USER:shop}
    password: ${POSTGRES_PASSWORD:shop}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: "pl.wit.shop.product.domain"
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
      show_sql: true