micronaut:
  application:
    name: shop
  server:
    port: 8030
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:swagger
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  openapi:
    views:
      spec: redoc.enabled=true,rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:4010/shop
    username: shop
    password: shop
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: "pl.wit.shop.product.domain"
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
      show_sql: true